# Generated by Django 5.2.4 on 2025-08-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('partner', 'Partner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
