# Generated by Django 5.2.5 on 2025-08-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_partner_approved',
            field=models.BooleanField(default=False),
        ),
    ]
