# Generated by Django 5.2.5 on 2025-08-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='partner_documents/')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.documenttype')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partner.partner')),
            ],
        ),
    ]
