# Generated by Django 5.2.5 on 2025-08-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partnerdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partner',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
