# Generated by Django 5.2.5 on 2025-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partner_address_partner_city_partner_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INITIAL_CREDIT', 'Initial Plan Credit'), ('TOP_UP', 'Wallet Top-up'), ('SERVICE_PAYMENT', 'Service Payment'), ('REFUND', 'Refund Credit'), ('EXPIRY', 'Expired Balance Reset'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=20),
        ),
    ]
